### ISSUE TITLE
Meer ademruimte

### ISSUE THREAD

**Issue by zoepje** [TygoWolven/the-client-website#1]
https://github.com/TygoWolven/the-client-website/blob/a9f8bed46644082c995ff12707085890adff12b6/familieoverzicht.html#L155

Je zou hier je code onder elkaar kunnen zetten en gebruik kunnen maken van tabs.

**Comment by TygoWolven** [comment]
Dit onderwerp heb ik behandeld in Isue#2. Thanks!
