### ISSUE TITLE
Meer ruimte in je code

### ISSUE THREAD

**Issue by iBadr49** [TygoWolven/the-client-website#2]
https://github.com/TygoWolven/the-client-website/blob/a9f8bed46644082c995ff12707085890adff12b6/familieoverzicht.html#L154-L159

Je kan beter de "li" tags onder elkaar tussen de "h3" "p" en "img", je kan ook een <alt> toevoegen voor de images!

**Comment by TygoWolven** [comment]
Alles onder elkaar is inderdaad overzichtelijker, bedankt voor de tip!

https://github.com/TygoWolven/the-client-website/blob/718b91d8c606322d7e76c2c47e5ef91cb9ade44b/familieoverzicht.html#L154-L164
