### ISSUE TITLE
Class namen 

### ISSUE THREAD

**Issue by TimOosterveer** [TygoWolven/the-client-website#3]
https://github.com/TygoWolven/the-client-website/blob/a9f8bed46644082c995ff12707085890adff12b6/familieoverzicht.html#L144C21-L144C37

Gebruik engelse namen voor classes, wat in de presentatie is besproken. Is familie overzicht een goede naam of kan dit anders?!

**Comment by TygoWolven** [comment]
Vanaf nu gebruik ik engelse classnamen. Check!

https://github.com/TygoWolven/the-client-website/blob/718b91d8c606322d7e76c2c47e5ef91cb9ade44b/familieoverzicht.html#L145

https://github.com/TygoWolven/the-client-website/blob/718b91d8c606322d7e76c2c47e5ef91cb9ade44b/familieoverzicht.html#L149
