### ISSUE TITLE
Veel witregels

### ISSUE THREAD

**Issue by Robin1224** [TygoWolven/the-client-website#4]
Het is niet per se fout, maar je gebruikt erg veel witregels. 

Zoals bijvoorbeeld in index.html; maar eigenlijk ook in de rest van de pagina's
```html
</head>
<body>

    <img src="./image/oba_20.png">

    <h1>Kies je profiel:</h1>

    <section class="profielen">
        <ul>
            <li><a href="./mijnoba.html"><img src="./image/AmberFoto.jpeg">Papa</a></li>
            <li><a href="./mijnoba.html"><img src="./image/AmberFoto.jpeg">Mama</a></li>
            <li><a href="./mijnoba.html"><img src="./image/AmberFoto.jpeg">Kind 1</a></li>
            <li><a href="./mijnoba.html"><img src="./image/AmberFoto.jpeg">Kind 2</a></li>
        </ul>
    </section>
    
</body>
```

Wanneer je veel witregels gebruikt, raken ze hun betekenis een beetje kwijt. Wanneer ieder element een witregel ertussen heeft, staan ze eigenlijk allemaal weer op dezelfde afstand van elkaar. Een witregel werkt (naar mijn mening) beter wanneer er minder in staan, omdat het dan een duidelijk verschil aangeeft tegenover elementen waar geen witregel tussen staat

**Comment by TygoWolven** [comment]
In mijn code conventies gebruik ik witregels voor nieuwe kopjes in de code. In dit geval komt er een nieuw kopje, de section. Om deze section zet ik witregels, daar binnen in niet. Ieder geval bedankt!
