### ISSUE TITLE
Id

### ISSUE THREAD

**Issue by TimOosterveer** [TygoWolven/the-client-website#5]
https://github.com/TygoWolven/the-client-website/blob/a9f8bed46644082c995ff12707085890adff12b6/depositos.html#L148

Waarom zit hier een id op?

**Comment by TygoWolven** [comment]
Ik heb hem weggehaald, die was inderdaad nutteloos!

https://github.com/TygoWolven/the-client-website/blob/718b91d8c606322d7e76c2c47e5ef91cb9ade44b/depositos.html#L146-L149
