### ISSUE TITLE
Style code in HTML

### ISSUE THREAD

**Issue by Robin1224** [TygoWolven/the-client-website#6]
In de HTML code van je familieoverzicht.html pagina, staat een style attribuut binnen je HTML code:

_line 59-64_
```html
    <li class="nav-link" style="background: #FF0000; border-radius: 6px;">
        <a href="./familieoverzicht.html">
             <i class='bx bx-group icon' style="color: #FFF;"></i>
             <span class="text nav-text" style="color: #FFF;">Familieoverzicht</span>
        </a>
    </li>
```

Het is beter om alle styling buiten de HTML te houden, en dit alleen in je CSS bestand te hebben staan. Als je een specifiek element andere styling wil geven, kun je er beter een class (of id) op zetten.

**Comment by TygoWolven** [comment]
Ik denk dat dit voor dat ene element prima is. Deze styling staat bij elke pagina op een andere tab. Dit zou betekenen dat ik anders veel meer css bestanden moet aanmaken voor elke pagina.

**Comment by Robin1224** [comment]
De reden dat ik dit issue inschiet is omdat het ingaat tegen een code conventie [Seperation of Concerns](https://google.github.io/styleguide/htmlcssguide.html#Separation_of_Concerns), en de reden dat ik alsnog een comment schrijf is omdat de oplossing makkelijker is dan het lijkt.

Een makkelijke manier om dit op te lossen, en geen nieuwe css bestanden aan te hoeven maken is om de specifieke stylings in een nieuwe class te zetten, zoals bijvoorbeeld `.active-tab`

Dan zou je in je css bestand alleen maar 1 extra class moeten maken:
```css
.active-tab {
    background: #FF0000; 
    border-radius: 6px;
}
```

In je HTML zou je dan vervolgens op iedere pagina bij de actieve tab de extra class `active-tab` toevoegen, in plaats van een style attribuut:
```html
<li class="nav-link active-tab">
    <a href="./familieoverzicht.html">
        <i class="bx bx-group icon" style="color: #FFF;"></i>
        <span class="text nav-text" style="color: #FFF;">Familieoverzicht</span>
    </a>
</li>
```

De andere twee style attributen op de `<i>` en `<span>` elementen kunnen ook makkelijk in je css bestand verwerkt worden door child selectors te gebruiken. Bijvoorbeeld door deze styling toe te voegen aan je css _(selector kiest alle `<i>` èn `<span>` elementen die een child zijn van alle elementen met class `active-tab`)_:
```css
.active-tab i, .active-tab span {
    color: #fff;
}
```

In je HTML hoef je vervolgens alleen de style attributen weg te laten, de rest gaat vanzelf, zolang je maar de active-tab class toevoegt aan het `<li>` element wat op die pagina de styling moet krijgen:
```html
<li class="nav-link active-tab">
    <a href="./familieoverzicht.html">
        <i class="bx bx-group icon"></i>
        <span class="text nav-text">Familieoverzicht</span>
    </a>
</li>
```

Dit zorgt ervoor dat de code alsnog aan de [Seperation of Concerns](https://google.github.io/styleguide/htmlcssguide.html#Separation_of_Concerns) conventie voldoet, maar dat je minimale code hoeft toe te voegen aan je css, en je ook geen extra css bestanden hoeft te maken.
